name: "nuxt-app"
services:
  postgres:
    container_name: nuxt-app
    image: postgres:latest
    environment:
      POSTGRES_DB: "nuxt-app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - '5432:5432'